### ISSUE TITLE
duplicate and pls start making some more consistent variable names

### ISSUE THREAD

**Issue by JSchrewe123** [Lukox/TBD#1]
https://github.com/Lukox/Mulitplayer-Head-Soccer/blob/9cacbe8ce7ef6b4d3fb52528342e1ebecfba2a2a/index.js#L9

**Comment by Lukox** [comment]
ratio!

pon., 28 lis 2022 o 19:56 jan ***@***.***> napisał(a):

**Comment by JSchrewe123** [comment]
Issue has not been adressed :(
but ...
fair enough
